In [1]:
import numpy as np
from activation_func import activation_func

## MLP

In [2]:
from MLP_ULTRA import MLP

epoch 1
x                   z_in           z                y_in     y
------------------  -------------  -------------  ------  ----
[[0.25 0.5  0.75]]  [[0.75 0.75]]  [[0.36 0.36]]    0.36  0.36
[[0.75 0.5  0.25]]  [[0.75 0.75]]  [[0.36 0.36]]    0.36  0.36
δ_H                δ_O  h(q)             o(q)
---------------  -----  ---------------  ---------
[[-0.01 -0.01]]  -0.04  [[-0.   -0.  ]   [[-0.01]
                         [-0.   -0.  ]    [-0.01]]
                         [-0.01 -0.01]]
[[-0.06 -0.06]]  -0.28  [[-0.05 -0.05]   [[-0.1]
                         [-0.03 -0.03]    [-0.1]]
                         [-0.02 -0.02]]
o = [[-0.11]
 [-0.11]]
h = [[-0.05 -0.05]
 [-0.03 -0.03]
 [-0.02 -0.02]]
Δv = [[0.02 0.02]
 [0.02 0.02]
 [0.01 0.01]]
Δw = [[0.06]
 [0.06]]
v = [[0.52 0.52]
 [0.52 0.52]
 [0.51 0.51]]
w = [[0.56]
 [0.56]]


### 2022 Example

In [3]:
X = np.array([[0.25, 0.5, 0.75], [0.75, 0.5, 0.25]])
y = np.array([[0.25], [0.75]])
input_size = X.shape[1]
hidden_size = 2
output_size = y.shape[1]

V = np.full((input_size, hidden_size), 0.5)
# V = []
W = np.full((hidden_size, output_size), 0.5)

# V0 = np.full((1, hidden_size), 0.5)
# W0 = np.full((1, output_size), 0.5)

# V = np.vstack((V0, V))
# W = np.vstack((W0, W))

hidden_act = activation_func.bipolar_sigmoid
de_hidden_act = activation_func.d_bipolar_sigmoid
output_act = activation_func.identity
de_output_act = activation_func.d_identity
mlp = MLP(
    input_size,
    hidden_size,
    output_size,
    activation_func_hidden=hidden_act,
    activation_func_output=output_act,
    derivative_act_hidden=de_hidden_act,
    derivative_act_output=de_output_act,
    batch_mode=True,
    bias=False,
    print_steps=True,
    decimal_point=3,
    init_weights=(V, W)
)
v,w = mlp.train(X, y, epochs=1, learning_rate=1.0)

epoch 1
x                   z_in           z                  y_in      y
------------------  -------------  ---------------  ------  -----
[[0.25 0.5  0.75]]  [[0.75 0.75]]  [[0.358 0.358]]   0.358  0.358
[[0.75 0.5  0.25]]  [[0.75 0.75]]  [[0.358 0.358]]   0.358  0.358
δ_H                   δ_O  h(q)               o(q)
-----------------  ------  -----------------  ---------
[[0.024 0.024]]     0.108  [[0.006 0.006]     [[0.039]
                            [0.012 0.012]      [0.039]]
                            [0.018 0.018]]
[[-0.085 -0.085]]  -0.392  [[-0.064 -0.064]   [[-0.14]
                            [-0.043 -0.043]    [-0.14]]
                            [-0.021 -0.021]]
o = [[-0.102]
 [-0.102]]
h = [[-0.058 -0.058]
 [-0.031 -0.031]
 [-0.004 -0.004]]
Δv = [[0.029 0.029]
 [0.015 0.015]
 [0.002 0.002]]
Δw = [[0.051]
 [0.051]]
v = [[0.529 0.529]
 [0.515 0.515]
 [0.502 0.502]]
w = [[0.551]
 [0.551]]


### 2021 Example

In [4]:
X = np.array([[0.25, 0.5, 0.25], [0.5, 0.25, 0.5]])
y = np.array([[0.5], [0.75]])

input_size = X.shape[1]
hidden_size = 2
output_size = y.shape[1]

V = np.full((input_size, hidden_size), 0.5)
W = np.full((hidden_size, output_size), 0.5)

V0 = np.full((1, hidden_size), 0.5)
W0 = np.full((1, output_size), 0.5)

V = np.vstack((V0, V))
W = np.vstack((W0, W))

hidden_act = activation_func.bipolar_sigmoid
de_hidden_act = activation_func.d_bipolar_sigmoid
output_act = activation_func.identity
de_output_act = activation_func.d_identity
mlp = MLP(
    input_size,
    hidden_size,
    output_size,
    activation_func_hidden=hidden_act,
    activation_func_output=output_act,
    derivative_act_hidden=de_hidden_act,
    derivative_act_output=de_output_act,
    batch_mode=False,
    bias=True,
    print_steps=True,
    decimal_point=3,
    init_weights=(V, W)
)
v, w = mlp.train(X, y, epochs=1, learning_rate=1.0)

epoch 1
x                   z_in       z                  y_in      y
------------------  ---------  ---------------  ------  -----
[[0.25 0.5  0.25]]  [[1. 1.]]  [[0.462 0.462]]   0.962  0.962
[[0.5  0.25 0.5 ]]  [[1. 1.]]  [[0.462 0.462]]   0.303  0.303
δ_H                 δ_O  Δv                 Δw          v                w
---------------  ------  -----------------  ----------  ---------------  ---------
[[0.091 0.091]]   0.462  [[-0.091 -0.091]   [[-0.462]   [[0.409 0.409]   [[0.038]
                          [-0.023 -0.023]    [-0.214]    [0.477 0.477]    [0.286]
                          [-0.045 -0.045]    [-0.214]]   [0.455 0.455]    [0.286]]
                          [-0.023 -0.023]]               [0.477 0.477]]
[[-0.05 -0.05]]  -0.447  [[0.05  0.05 ]     [[0.447]    [[0.46  0.46 ]   [[0.485]
                          [0.025 0.025]      [0.207]     [0.502 0.502]    [0.493]
                          [0.013 0.013]      [0.207]]    [0.467 0.467]    [0.493]]
                    

In [5]:
input_size = 3
hidden_size = 2
output_size = 2
X = np.array([[1, 1, 1], [1, -1, -1]])
y = np.array([[1, 1], [-1, -1]])

V = np.array([
    [0.22, 0.57],
    [0.7, 0.21],
    [0.18, 0.11],
    [0.38, 0.44]
])

W = np.array([
    [0.09, 0.81],
    [0.77, 0.86],
    [0.17, 0.29]
])
l

hidden_act = activation_func.bipolar_sigmoid
de_hidden_act = activation_func.d_bipolar_sigmoid
output_act = activation_func.bipolar_sigmoid
de_output_act = activation_func.d_bipolar_sigmoid

mlp = MLP(
    input_size,
    hidden_size,
    output_size,
    activation_func_hidden=hidden_act,
    activation_func_output=output_act,
    derivative_act_hidden=de_hidden_act,
    derivative_act_output=de_output_act,
    batch_mode=False,
    bias=True,
    print_steps=True,
    init_weights=(V, W)
)
v, w = mlp.train(X, y, epochs=1, learning_rate=0.2)

epoch 1
x             z_in           z              y_in           y
------------  -------------  -------------  -------------  -------------
[[1 1 1]]     [[1.48 1.33]]  [[0.63 0.58]]  [[0.67 1.52]]  [[0.32 0.64]]
[[ 1 -1 -1]]  [[0.36 0.23]]  [[0.18 0.11]]  [[0.32 1.02]]  [[0.16 0.47]]
δ_H              δ_O              Δv               Δw               v              w
---------------  ---------------  ---------------  ---------------  -------------  -------------
[[-0.1  -0.03]]  [[-0.3  -0.11]]  [[0.02 0.01]     [[0.06 0.02]     [[0.24 0.58]   [[0.15 0.83]
                                   [0.02 0.01]      [0.04 0.01]      [0.72 0.22]    [0.81 0.87]
                                   [0.02 0.01]      [0.04 0.01]]     [0.2  0.12]    [0.21 0.3 ]]
                                   [0.02 0.01]]                      [0.4  0.45]]
[[0.46 0.14]]    [[0.56 0.57]]    [[-0.09 -0.03]   [[-0.11 -0.11]   [[0.15 0.55]   [[0.04 0.72]
                                   [-0.09 -0.03]    [-0.02 -0.0

## ConvNet

In [6]:
from activation_func import activation_func
from pooling import pooling
from convNet import convNet

Z_in(1) = -3.45
Z_in(2) = -2.5
Z_in(3) = -1.5
Z_in(4) = -0.25
Z_in(5) = 0.65
Z_in(6) = 1.9
Z_in = [-3.45 -2.5  -1.5  -0.25  0.65  1.9 ]
After applying hidden layer activation function:
Z = [0.   0.   0.   0.   0.65 1.9 ]
Output after pooling:
y = [0.   0.   1.27]
out_H: [0.   0.   0.   0.   0.65 1.9 ]
out_O: [0.   0.   1.27]


### Example 1

In [7]:
x = np.array([-2.0, -1.8, -1.4, -0.6, -0.2, 0.4, 0.8, 1.6])

conv_filter = np.array([0.75, 0.5, 0.75])

conv1d = convNet(
    conv_filter=conv_filter,
    stride_conv=1,
    pooling_type=pooling.average_pooling,
    pooling_size=2,
    stride_pooling=2,
    decimal_point=3,
    act_f=activation_func.Elu,
)

out_H, out_O = conv1d.forward(x)


Z_in(1) = -3.45
Z_in(2) = -2.5
Z_in(3) = -1.5
Z_in(4) = -0.25
Z_in(5) = 0.65
Z_in(6) = 1.9
Z_in = [-3.45 -2.5  -1.5  -0.25  0.65  1.9 ]
After applying hidden layer activation function:
Z = [-0.968 -0.918 -0.777 -0.221  0.65   1.9  ]
Output after pooling:
y = [-0.943 -0.499  1.275]


### Example 2

In [8]:
x = np.array([-2.0, -1.8, -1.4, -0.6, -0.2, 0.4, 0.8, 1.6])

conv_filter = np.array([0.75, 0.5, 0.75,0.25])
weights = [0.3, 0.7]

conv1d = convNet(
    conv_filter=conv_filter,
    stride_conv=1,
    pooling_type=pooling.weighted_pooling,
    pooling_params=a,
    pooling_size=2,
    stride_pooling=2,
    decimal_point=3,
    act_f=activation_func.Elu,
)

out_H, out_O = conv1d.forward(x)


Z_in(1) = -3.45
Z_in(2) = -2.5
Z_in(3) = -1.5
Z_in(4) = -0.25
Z_in(5) = 0.65
Z_in(6) = 1.9
Z_in = [-3.45 -2.5  -1.5  -0.25  0.65  1.9 ]
After applying hidden layer activation function:
Z = [-0.968 -0.918 -0.777 -0.221  0.65   1.9  ]
Output after pooling:
y = [-0.933 -0.388  1.525]
